spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://github.com/ckrbqja/traffic-monitoring-appofapps.git
    targetRevision: HEAD
    
apps:
  - loki-stack
  - traffic-test-moni-master

